train:
  model_name: 'resnet50'
  pretrained_dir: './models/weights'
  num_workers: 8
  batch_size: 64
  save_model_interval: 5
  num_epochs: 15
  device: 'cpu'
  lr: 1e-3
  validation:
    interval: 1
    num_iterations: 100

optimizer:
  name: 'MAB_epsilon_greedy'
  MAB:
    type: 'epsilon_greedy'
  layerwise:
    idx: -1

models:
  save_dir: './models/saves'
  model_checkpoint: 'resnet18'

datasets:
  name: 'cifarc'
  split: [0.75, 0.25]
  shuffle: True
  dir: './datasets/data'
  cifar:
    corruption: 'gaussian_noise'

logging:
  dir: './logs'