train:
  model_name: 'resnet18'
  dataset_name: 'cifar'
  pretrained_dir: './models/weights'
  num_workers: 4
  batch_size: 4
  dataroot: 'data'
  corruption: 'gaussian_noise'
  save_model_interval: 100
  num_epochs: 500
  device: 'cpu'
  validation:
    interval: 10
    num_iterations: 100

models:
  save_dir: './models/saves'

datasets:
  cifar:
    dir: './datasets/data'

logging:
  dir: './logs'