train:
  model_name: 'resnet18'
  dataset_name: 'cifar'
  pretrained_dir: './models/weights'
  num_workers: 8
  batch_size: 64
  corruption: 'gaussian_noise'
  save_model_interval: 10
  num_epochs: 15
  device: 'cpu'
  validation:
    interval: 1
    num_iterations: 100

models:
  save_dir: './models/saves'

datasets:
  cifar:
    dir: './datasets/data'

logging:
  dir: './logs'